services:
  web-dev:
    build:
      context: .
      target: dev
    container_name: duo-web-dev
    profiles:
      - dev
    network_mode: host
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    env_file:
      - .env

  web-prod:
    build:
      context: .
      target: prod
    container_name: duo-web-prod
    profiles:
      - prod
    network_mode: host
    env_file:
      - .env

volumes:
  cargo_cache:
  target_cache:
