//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub login: String,
    pub password: String,
    pub display_name: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::roles_assigned::Entity")]
    RolesAssigned,
    #[sea_orm(has_one = "super::savefile::Entity")]
    Savefile,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
}

impl Related<super::roles_assigned::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolesAssigned.def()
    }
}

impl Related<super::savefile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Savefile.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
