//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)] //Включити до цієї структури автоматичну реалізацію вказаних ознак
#[sea_orm(table_name = "accounts")] //Назва відповідної таблиці в базі даних, при компіляції додає до коду структуру ActiveModel,
//що відтворює Model, але з типами даних оберненими в ActiveValue
/*
    pub struct ActiveModel {
        pub id: ActiveValue<i64>,
        pub created_at: ActiveValue<DateTime<FixedOffset>>,
        pub uuid: ActiveValue<Uuid>,
        pub login: ActiveValue<String>,
        pub password: ActiveValue<String>,
        /* … */
    }
*/
pub struct Model { //Структура, що описує стовпці таблиці, атрибути вказують властивості стовпців в базі даних
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub login: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub games_played: i64,
    pub points: i64,
    pub cards_had: i64,
    pub wins: i32,
    pub loses: i32,
    pub max_points: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation { //Список таблиць з якими ця таблиця має з'єднання
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {} //Стандартна реалізація ActiveModelBehavior для ActiveModel
