//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::roles_assigned::Entity")]
    RolesAssigned,
}

impl Related<super::roles_assigned::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolesAssigned.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
